CREATE TABLE AUTHOR_table
(
AUTHOR_ID INT PRIMARY KEY,
AUTHOR_NAME VARCHAR(MAX),
COUNTRY VARCHAR(MAX)
);

CREATE TABLE BOOK_table
(
BOOK_ID INT PRIMARY KEY,
BOOK_TITLE VARCHAR(MAX),
AUTHORID INT
FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(AUTHOR_ID)
);

INSERT INTO AUTHOR_table(AUTHOR_ID,AUTHOR_NAME,COUNTRY) VALUES 
(1,'RAJU','INDIA'),
(2,'PRAKASH','INDIA'),
(3,'JOSEPH','USA');

INSERT INTO BOOK_table(BOOK_ID,BOOK_TITLE,AUTHORID) VALUES
(101,'SWACH',1),
(102,'PREAM',2),
(103,'WARRIOR',3);


SELECT B.BOOK_TITLE,A.AUTHOR_NAME,A.COUNTRY
FROM BOOK_table AS B
INNER JOIN
AUTHOR_table AS A
ON B.AUTHORID=A.AUTHOR_ID
